### ISSUE TITLE
Main camera view glitch

### ISSUE THREAD

**Issue by longwolfdude** [Snow1226/CameraPlus#17]
Whenever I use a mod to "RemoveHealthWarning" (such as gattagofast or tweaks55) a glitch happens where the camera looks to be really far away and distant object proportions are way off.

I am using version 5.2.1

![Screenshot (405)](https://user-images.githubusercontent.com/74474209/122595793-cb65af80-d01d-11eb-9a5a-f15cc4de5584.png)
![Screenshot (406)](https://user-images.githubusercontent.com/74474209/122595834-dc162580-d01d-11eb-822e-1a204760353a.png)

**Comment by Snow1226** [comment]
I confirmed the symptomatology.
However, because it was interrupted during the initialization process
The fix will cause problems for people who don't use "Remove Health Warning".

I will think about the correspondence, but I can not respond immediately.
Load the profile after startup.
Or please use Camera2.

**Comment by longwolfdude** [comment]
I understand, take your time. It's a minor bug anyway. I just wanted to bring this to your attention. (whether it gets fixed or not)
For now, I'll just set as false for "RemoveHealthWarning" in the gattagofast settings.

(_PS:Thanks for keeping this mod alive despite very few people using it._)

**Comment by Snow1226** [comment]
I was able to address this issue.
Check with the next release, version 6.0.0.
